# Auto-Update Project Status Script
# Запуск: ./update-status.ps1

$ErrorActionPreference = "Stop"

Write-Host "🔄 Оновлення статусу проєкту Yana.Diia.AI..." -ForegroundColor Cyan

# Get current date/time
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
$demoDate = Get-Date "2025-11-29"
$today = Get-Date
$daysLeft = ($demoDate - $today).Days

# Count files
$appFiles = (Get-ChildItem -Path "app" -Recurse -File -Filter "*.tsx").Count
$componentFiles = (Get-ChildItem -Path "components" -Recurse -File -Filter "*.tsx").Count
$libFiles = (Get-ChildItem -Path "lib" -Recurse -File -Filter "*.ts").Count
$configFiles = (Get-ChildItem -Path "config" -Recurse -File -Filter "*.ts").Count
$totalFiles = $appFiles + $componentFiles + $libFiles + $configFiles

# Count lines of code
$tsxFiles = Get-ChildItem -Path . -Recurse -Include *.tsx,*.ts -Exclude node_modules
$totalLines = ($tsxFiles | Get-Content | Measure-Object -Line).Lines

# Check npm dependencies
Write-Host "📦 Перевірка npm..." -ForegroundColor Yellow
$npmStatus = "❌ Не перевірено"
try {
    $npmCheck = npm list 2>&1 | Out-String
    if ($npmCheck -match "found 0 vulnerabilities") {
        $npmStatus = "✅ 0 vulnerabilities"
    }
} catch {
    $npmStatus = "⚠️ npm не доступний"
}

# Check if dev server can start
Write-Host "🚀 Перевірка dev server..." -ForegroundColor Yellow
$devServerStatus = "⏳ Не тестовано"

# Generate status report
$statusContent = @"
# 🎯 Yana.Diia.AI - Auto-Updated Status

**Останнє оновлення**: $timestamp  
**Днів до Demo Day**: **$daysLeft днів** 🔥  
**Автоматично згенеровано**: update-status.ps1

---

## 📊 Code Metrics

| Metric | Value |
|--------|-------|
| **App Files (.tsx)** | $appFiles |
| **Components (.tsx)** | $componentFiles |
| **Lib Files (.ts)** | $libFiles |
| **Config Files (.ts)** | $configFiles |
| **Total TypeScript Files** | $totalFiles |
| **Total Lines of Code** | $totalLines |

---

## 🔧 Build Status

| Check | Status |
|-------|--------|
| NPM Dependencies | $npmStatus |
| Dev Server | $devServerStatus |
| TypeScript Compile | ⏳ Checking... |
| Production Build | ⏳ Not tested |

---

## ✅ Features Checklist

- [x] Landing Page
- [x] Dashboard
- [x] Platform Navigation
- [x] Lego Constructor
- [x] AI Debate Chamber ⭐
- [x] BRD Pipeline
- [x] Evaluation Lab
- [x] Quantum Optimizer
- [x] Blockchain Audit
- [x] Dev Panel
- [x] Mock LLM Provider

**Готовність**: 11/11 (100%)

---

## 🎬 Demo Day Countdown

**$daysLeft днів до перемоги!**

### Priority Tasks:
- [ ] Fix PowerShell execution policy
- [ ] Test dev server
- [ ] Record backup video
- [ ] Rehearse presentation (3x)
- [ ] Prepare Google Slides
- [ ] Test on Demo Day laptop

---

## 📈 Progress Timeline

### Done ✅
- Day 1: Project Setup + Mock Mode
- Day 2: Lego Constructor
- Day 3: AI Debate Chamber
- Day 4: BRD Parser + Flow Generator
- Day 5: LLM Evaluator
- Day 6: Quantum Optimizer
- Day 7: Glagolitic Crypto

### Testing Phase ⏳
- [ ] Local dev server
- [ ] All routes accessible
- [ ] Konami Code works
- [ ] Animations smooth
- [ ] No console errors

### Final Prep 🚀
- [ ] Video recording
- [ ] Slide deck
- [ ] Rehearsal
- [ ] Deployment (optional)

---

**Generated by**: update-status.ps1  
**Next update**: Run ``./update-status.ps1`` again  
**Manual status**: See PROJECT_STATUS.md
"@

# Write to file
$statusContent | Out-File -FilePath "AUTO_STATUS.md" -Encoding UTF8

Write-Host "✅ Статус оновлено!" -ForegroundColor Green
Write-Host "📄 Файл: AUTO_STATUS.md" -ForegroundColor Cyan
Write-Host "📊 Files: $totalFiles | Lines: $totalLines" -ForegroundColor White
Write-Host "⏰ Days to Demo: $daysLeft" -ForegroundColor Yellow

# Optional: Open the file
Write-Host ""
Write-Host "Відкрити AUTO_STATUS.md? (y/n)" -ForegroundColor Magenta
$open = Read-Host
if ($open -eq "y") {
    Start-Process "AUTO_STATUS.md"
}
